Update publish.yml

diff --git a/.github/workflows/publish.yml b/.github/workflows/publish.yml
--- a/.github/workflows/publish.yml
+++ b/.github/workflows/publish.yml
@@ -18,7 +18,7 @@ jobs:
         with:
           fetch-depth: 0
 
-      - name: Update package version from plugin
+      - name: Update package.json & README version from plugin
         id: version_update
         run: |
           # Define plugin filename
@@ -26,6 +26,10 @@ jobs:
 
           # Extract current version from plugin file
           version=$(grep -oP 'Version:\s*\K[0-9]+\.[0-9]+\.[0-9]+' "$plugin_file")
+          if [ -z "$version" ]; then
+            echo "Version not found in plugin file. Exiting."
+            exit 1
+          fi
           echo "Current version: $version"
 
           # Set version as an environment variable
@@ -43,11 +47,15 @@ jobs:
           echo "$plugin_data"
 
           # Write plugin data to README.md
-          escaped_plugin_data=$(echo "$plugin_data" | sed 's/[&/\]/\\&/g' | awk '{printf "%s\\n", $0}')
-          sed -i "/<!-- BEGIN PLUGIN DATA -->/,/<!-- END PLUGIN DATA -->/c\\
-          <!-- BEGIN PLUGIN DATA -->\\
-          $escaped_plugin_data\\
-          <!-- END PLUGIN DATA -->" README.md
+          if [ -f "README.md" ]; then
+            escaped_plugin_data=$(echo "$plugin_data" | sed 's/[&/\]/\\&/g' | awk '{printf "%s\\n", $0}')
+            sed -i "/<!-- BEGIN PLUGIN DATA -->/,/<!-- END PLUGIN DATA -->/c\\
+            <!-- BEGIN PLUGIN DATA -->\\
+            $escaped_plugin_data\\
+            <!-- END PLUGIN DATA -->" README.md
+          else
+            echo "README.md not found, skipping plugin data update in README.md"
+          fi
 
       - name: Commit version changes to dev
         run: |
@@ -65,7 +73,7 @@ jobs:
 
       - name: Merge dev into main
         run: |
-          git merge origin/dev --no-ff -m "Merging updated version from dev to main" || { echo "Error: Merge failed"; exit 1; }
+          git merge origin/dev --no-ff -m "Merging from dev to main" || { echo "Error: Merge failed"; exit 1; }
 
       - name: Push changes to main branch
         run: |
